name: Laravel

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, bcmath, xml, curl, sqlite

      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: make install

      - name: Generate application key
        run: php artisan key:generate

      - name: Set permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run quality checks
        run: make quality
